### ISSUE TITLE
About calculating the optimal update

### ISSUE THREAD

**Issue by GreenOctopus-gate** [keenan-burnett/yeti_radar_odometry#4]
Hi Keenan Burnett, 
I really enjoy the paper and the code you released.
There is one thing that I do not really understand because of my level of mathematics. I would like to ask you for answers or some math materials that need to be studied. So for the optimal update, the code lines as:
```
A += G.transpose() * G;
b += G.transpose() * ebar;
```
`Eigen::VectorXd delta_w = A.bdcSvd(Eigen::ComputeThinU| Eigen::ComputeThinV).solve(b);`

In the paper, the optimal update still need a element: R(cart,m), the covariance in the local Cartesian frame. I don't know why R(cart,m) do not appear.Sorry, I am a beginner in the field of SLAM, I don't know where to start with the understanding here.
Thanks for your time and the great resource.

**Comment by keenan-burnett** [comment]
You're correct that R_cart is missing from the implementation.
It's been a couple years, but if I recall correctly, including the R_cart covariances did not substantially improve performance.
It would be interesting to try putting the covariance back in while also including a robust cost function.

In our recent work, we use STEAM instead of MC-RANSAC to do motion and Doppler compensation for radar odometry:
https://arxiv.org/abs/2203.10174
In that more up-to-date work, we use a constant diagonal matrix for R_cart (and treat it as a tuning parameter).

**Comment by GreenOctopus-gate** [comment]
@keenan-burnett Thank you!!!
